[package]
name = "leader_election_project"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
rand = "0.8"
sysinfo = "0.32"
lazy_static = "1.4"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }

