[package]
name = "image_server"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
futures = "0.3.31"
lazy_static = "1.5.0"
serde = { version = "1.0.215", features = ["derive"] }
sysinfo = "0.32.0"
tokio = { version = "1.41.1", features = ["full"] }
